name: Build
on: [push]
jobs:
  build-on-openbsd:
    runs-on: macos-10.15
    steps:
    # - name: Vagrant-VirtualBox-with-repos-Vagrantfile
      # uses: kentahikaru/github-action-vagrant--vagrantfile-from-repository@v1
    - run: |
        run() {
          printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
          $@
        }
        run pwd
        run ls
        run ls /Users/runner/work/vag/
        echo 'set -e' >> shell.sh
        export -p | grep 'GITHUB_' >> shell.sh
        echo "cd /home/vagrant/${GITHUB_REPOSITORY}" >> shell.sh
        cat >> shell.sh <<'EOF'
        run() {
          printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
          $@
        }
        ${{inputs.run}}
        EOF
        run echo ${GITHUB_WORKSPACE}
        export NEWCONFIG="config.vm.synced_folder \"${GITHUB_WORKSPACE}\", \"\/home\/vagrant\/${GITHUB_REPOSITORY}\", type: \"rsync\""
        sed -i -e "s|config.vm.synced_folder.*|$NEWCONFIG|g" Vagrantfile
        run cat Vagrantfile
        run cat shell.sh
        run vagrant up --provision
      shell: bash